import { randomUUID } from "crypto";
import { QueryInterface } from "sequelize";

// Seeds the initial partner directory researched for the Nigerian-graduate lead-gen
// push -- see the Partner Pipeline plan this was built for. Idempotent by name: skips
// entirely if any partners already exist, so this never duplicates rows on a second
// deploy or clobbers changes made through the admin UI after the first deploy.
module.exports = {
  up: async (queryInterface: QueryInterface) => {
    const [existing] = (await queryInterface.sequelize.query(
      "SELECT id FROM partners LIMIT 1",
    )) as [Array<{ id: string }>, unknown];
    if (existing.length > 0) {
      return;
    }

    await queryInterface.bulkInsert("partners", [
      {
        id: randomUUID(),
        name: "Jobberman",
        category: "Job Board",
        sector: "General",
        url: "jobberman.com",
        contact: null,
        cost: "Free tier; sponsored placement available",
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Biggest, most employer-trusted board -- banks, telecoms & FMCGs post here directly. No public email found -- use https://www.jobberman.com/employer/call-requests or https://www.jobberman.com/contact-us.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "MyJobMag",
        category: "Job Board",
        sector: "General",
        url: "myjobmag.com",
        contact: "services@myjobmag.com",
        cost: "Free tier; sponsored placement available",
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Verified listings plus career advice, salary insights, interview tips.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Hot Nigerian Jobs",
        category: "Job Board",
        sector: "General",
        url: "hotnigerianjobs.com",
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Updated almost hourly -- highest volume. Contact email is Cloudflare-protected on their site; use the form at hotnigerianjobs.com/contact_us.php.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "NGCareers",
        category: "Job Board",
        sector: "General",
        url: "ngcareers.com",
        contact: null,
        cost: "Free employer access",
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "CV search, company reviews, training resources. Acquired by Jobberman in 2020 -- consider routing inquiries through Jobberman instead.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "NaijaJobPortal",
        category: "Job Board",
        sector: "General",
        url: "naijajobportal.com.ng",
        contact: "info@naijajobportal.com.ng",
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Has a graduate-trainee filter built for NYSC corps members. General support: support@naijajobportal.com.ng; partnerships: info@naijajobportal.com.ng.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Jobzilla NG",
        category: "Job Board",
        sector: "General",
        url: "jobzilla.ng",
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Aggregates across sectors, including oil & gas. Their contact page blocked automated access -- check jobzilla.ng directly for a partnerships contact.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "NYSC SAED Programme",
        category: "NYSC / SAED",
        sector: null,
        url: "nysc.gov.ng/saed.html",
        contact: "info@nysc.gov.ng",
        cost: "Vendor/provider registration -- cost TBD",
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "National Skills Acquisition & Entrepreneurship Development programme. info@nysc.gov.ng is NYSC's general HQ contact, not SAED-specific -- ask to be routed to SAED. A self-service training-centre/provider registration flow also exists at saed.nysc.org.ng/trainingCentreRegistration -- check that first, it may skip email outreach entirely.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Lagos -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "admissions@unilag.edu.ng is documented but that's the Admissions office, not Careers -- find the correct careers/alumni-office contact before outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Ibadan -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Has a dedicated Career Development & Counselling Centre (career.ui.edu.ng). A contact address resembling cdcc@ui.edu.ng appears on their site, but the exact form was ambiguous when checked -- verify on career.ui.edu.ng before sending, rather than trusting this note.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Ahmadu Bello University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Obafemi Awolowo University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Nigeria, Nsukka -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Benin -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Port Harcourt -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: null,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "NYSC Batch Facebook Groups",
        category: "Community Channel",
        sector: null,
        url: null,
        contact: null,
        cost: "Free (organic) or group-admin sponsor post",
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Search \"NYSC Batch [X] Stream [Y]\" groups per posting period. Always check the group's own self-promotion rules first.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Campus Ambassador Network",
        category: "Community Channel",
        sector: null,
        url: null,
        contact: null,
        cost: "Incentive/commission per referral, TBD",
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Recruit 1-2 paid or incentivized ambassadors per target university rather than trying to join every departmental group directly.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "African Aviation and Aerospace University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Abubakar Tafawa Balewa University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Adeyemi Federal University of Education -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Admiralty University Ibusa -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Air Force Institute of Technology -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Alex Ekwueme Federal University Ndufu Alike Ikwo -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Alvan Ikoku Federal University of Education -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Bayero University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Birnin Kebbi -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Dutse -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Dutsin-Ma -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Gashua -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Gusau -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Kashere -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Lokoja -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Lafia -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Agriculture Abeokuta -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Agriculture Mubi -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Agriculture Zuru -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Applied Sciences Kachia -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Education Pankshi -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Education Zaria -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Health Sciences Azare -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Petroleum Resources Effurun -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Technology Akure -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Technology Ikot Abasi -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Technology Minna -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Technology Owerri -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University of Transportation Daura -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Otuoke -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Oye-Ekiti -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Federal University Wukari -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Joseph Sarwuan Tarka University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Michael Okpara University of Agriculture Umudike -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Modibbo Adama University Yola -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "National Open University of Nigeria -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Nigeria Police Academy Wudil -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Nigerian Army University Biu -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Nigerian Defence Academy -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Nigerian Maritime University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Nnamdi Azikiwe University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Tai Solarin Federal University of Education -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Abuja -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Calabar -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Ilorin -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Jos -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Maiduguri -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "University of Uyo -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Usmanu Danfodiyo University -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: randomUUID(),
        name: "Yusuf Maitama Sule Federal University of Education Kano -- Careers/Alumni Office",
        category: "University Career Centre",
        sector: null,
        url: null,
        contact: null,
        cost: null,
        status: "not-started",
        last_contacted: null,
        renewal_date: null,
        notes: "Find the current careers/alumni-office contact before drafting outreach.",
        created_at: new Date(),
        updated_at: new Date(),
      },
    ]);
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkDelete("partners", {});
  },
};
