import JSZip from "jszip";
import { ApiError } from "../utils/ApiError";
import { logger } from "../utils/logger";
import { AiDetectionResult, analyseText } from "./aiContentDetector.service";

export const AI_DETECTED_TITLE = "AI-Generated Answer Detected — Submission Not Accepted";
export const AI_DETECTED_INSTRUCTION =
  "Your answer appears to have been generated by an AI tool. Please rewrite it in your own words, based on what you learned in the lessons, and resubmit.";
export const AI_DETECTED_CODE = "AI_GENERATED_CONTENT";

interface UploadedFile {
  buffer: Buffer;
  originalname: string;
  mimetype: string;
}

const DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

// Pulls readable text out of an uploaded file so it can be checked. Returns null when the
// format can't be read (legacy .doc, images) or the file is corrupt -- an unreadable file
// is never a reason to block a submission, only the text we can actually assess is.
export async function extractTextFromFile(file: UploadedFile): Promise<string | null> {
  try {
    if (file.mimetype === "text/plain") {
      return file.buffer.toString("utf8");
    }
    if (file.mimetype === DOCX_MIME) {
      const zip = await JSZip.loadAsync(file.buffer);
      const xml = await zip.file("word/document.xml")?.async("string");
      if (!xml) return null;
      return xml
        .replace(/<\/w:p>/g, "\n")
        .replace(/<w:tab\/>/g, " ")
        .replace(/<[^>]+>/g, "")
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&apos;/g, "'");
    }
    if (file.mimetype === "application/pdf") {
      // pdfjs-dist's legacy build is the CommonJS-compatible one; no worker/canvas is needed
      // just to read text.
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const pdfjs = require("pdfjs-dist/legacy/build/pdf.js");
      const doc = await pdfjs.getDocument({
        data: new Uint8Array(file.buffer),
        useSystemFonts: true,
        isEvalSupported: false,
      }).promise;
      const pages: string[] = [];
      const pageLimit = Math.min(doc.numPages, 60);
      for (let i = 1; i <= pageLimit; i += 1) {
        const page = await doc.getPage(i);
        const content = await page.getTextContent();
        pages.push(content.items.map((item: { str?: string }) => item.str ?? "").join(" "));
      }
      return pages.join("\n");
    }
    return null;
  } catch (err) {
    logger.warn(`Could not extract text from "${file.originalname}" for the originality check: ${String(err)}`);
    return null;
  }
}

export interface OriginalityInput {
  submissionText?: string | null;
  file?: UploadedFile;
}

// Runs before a submission is saved (assignments and capstones alike). Checks the typed
// answer and the attached file separately, so a clean file can't hide a generated body or
// vice versa, and throws a 422 the frontend turns into the "AI-Generated Answer Detected"
// dialog. Nothing is stored -- the file isn't written to disk -- when it throws.
export async function assertSubmissionIsOriginal(input: OriginalityInput): Promise<void> {
  const checks: Array<{ source: "answer" | "file"; result: AiDetectionResult }> = [];

  if (input.submissionText && input.submissionText.trim()) {
    checks.push({ source: "answer", result: analyseText(input.submissionText) });
  }
  if (input.file) {
    const fileText = await extractTextFromFile(input.file);
    if (fileText && fileText.trim()) {
      checks.push({ source: "file", result: analyseText(fileText) });
    }
  }

  const flagged = checks.find((c) => c.result.likelyAi);
  if (!flagged) return;

  // Log the reasons for staff -- never the candidate's text.
  logger.info(
    `AI-generated submission blocked (${flagged.source}): score ${flagged.result.score}, ${flagged.result.signals.join("; ")}`,
  );
  throw new ApiError(422, AI_DETECTED_TITLE, {
    code: AI_DETECTED_CODE,
    source: flagged.source,
    instruction: AI_DETECTED_INSTRUCTION,
  });
}
