import { Router } from "express";
import { adminRouter } from "./admin.routes";
import { assignmentsRouter } from "./assignments.routes";
import { assignmentSubmissionsRouter } from "./assignmentSubmissions.routes";
import { authRouter } from "./auth.routes";
import { capstonesRouter } from "./capstones.routes";
import { capstoneSubmissionsRouter } from "./capstoneSubmissions.routes";
import { coursesRouter } from "./courses.routes";
import { enrollmentsRouter } from "./enrollments.routes";
import { healthRouter } from "./health.routes";
import { instructorRouter } from "./instructor.routes";
import { leadsRouter } from "./leads.routes";
import { lessonsRouter } from "./lessons.routes";
import { modulesRouter } from "./modules.routes";
import { quizAttemptsRouter } from "./quizAttempts.routes";
import { quizzesRouter } from "./quizzes.routes";
import { usersRouter } from "./users.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/courses", coursesRouter);
apiRouter.use("/modules", modulesRouter);
apiRouter.use("/lessons", lessonsRouter);
apiRouter.use("/enrollments", enrollmentsRouter);
apiRouter.use("/assignments", assignmentsRouter);
apiRouter.use("/assignment-submissions", assignmentSubmissionsRouter);
apiRouter.use("/instructor", instructorRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/quizzes", quizzesRouter);
apiRouter.use("/quiz-attempts", quizAttemptsRouter);
apiRouter.use("/capstones", capstonesRouter);
apiRouter.use("/capstone-submissions", capstoneSubmissionsRouter);
apiRouter.use("/leads", leadsRouter);
