import { z } from "zod";

// Exact matches only (case-insensitive) -- catches the passwords people actually type
// when a form merely demands "8+ characters", not a general strength estimator. Includes
// this app's own former seed-admin password (see docs/DEPLOYMENT.md) since that value has
// been publicly documented in this repo's history.
const COMMON_WEAK_PASSWORDS = new Set([
  "password",
  "password1",
  "password123",
  "12345678",
  "123456789",
  "1234567890",
  "qwerty123",
  "qwertyuiop",
  "letmein123",
  "iloveyou1",
  "admin1234",
  "welcome123",
  "changeme123",
  "abc123456",
  "football1",
  "monkey123",
]);

const passwordSchema = z
  .string()
  .min(10, "Password must be at least 10 characters")
  .refine((val) => /[a-zA-Z]/.test(val) && /[0-9]/.test(val), {
    message: "Password must include both letters and numbers",
  })
  .refine((val) => !COMMON_WEAK_PASSWORDS.has(val.toLowerCase()), {
    message: "This password is too common, please choose a different one",
  });

export const LOCATIONS = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Federal Capital Territory",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Nigeria",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

// Values are course slugs (not display titles) so a stored value can be used directly
// to redirect to the real course page after registration, e.g. /courses/${courseInterest}.
export const COURSE_INTERESTS = [
  "cyber-security-fundamentals",
  "social-media-management-content",
  "digital-marketing",
  "gis-and-drone-mapping",
  "renewable-energy-digital-systems",
  "hse-fundamentals",
] as const;

// Registration status offered on the register form. Must match
// frontend/src/features/auth/RegisterPage.tsx's REGISTRATION_STATUSES exactly -- the
// register request is rejected if the submitted value isn't in this list.
export const REGISTRATION_STATUSES = ["Graduate", "Current Student", "Non-Graduate"] as const;

// Nigerian universities offered on the lead form -- federal, state and private, sorted
// alphabetically. Must match backend/src/marketing/welcome.html's <select> exactly -- the
// leads request is rejected if the submitted value isn't in this list. (No longer used by
// the register form, which now collects REGISTRATION_STATUSES instead.)
export const UNIVERSITIES = [
  "Abdulkadir Kure University",
  "Abia State University",
  "Abiola Ajimobi Technical University",
  "Abubakar Tafawa Balewa University",
  "Achievers University",
  "Adamawa State University",
  "Adekunle Ajasin University",
  "Adeleke University",
  "Adeyemi Federal University of Education",
  "Admiralty University Ibusa",
  "Afe Babalola University",
  "African Aviation and Aerospace University",
  "African University of Science and Technology",
  "Ahmadu Bello University",
  "Ahman Pategi University",
  "Air Force Institute of Technology",
  "Ajayi Crowther University",
  "Akwa Ibom State University",
  "Al-Ansar University Maiduguri",
  "Al-Hikmah University",
  "Al-Qalam University",
  "Alex Ekwueme Federal University Ndufu Alike Ikwo",
  "Aliko Dangote University of Science and Technology",
  "Alvan Ikoku Federal University of Education",
  "Ambrose Alli University",
  "American University of Nigeria",
  "Anchor University",
  "Arthur Jarvis University",
  "Ave Maria University",
  "Babcock University",
  "Bauchi State University",
  "Bayelsa Medical University",
  "Bayero University",
  "Baze University",
  "Bells University of Technology",
  "Benson Idahosa University",
  "Benue State University",
  "Bingham University",
  "Borno State University",
  "Bowen University",
  "Caleb University",
  "Caritas University",
  "CETEP City University",
  "Chrisland University",
  "Christopher University",
  "Chukwuemeka Odumegwu Ojukwu University",
  "Clifford University",
  "Coal City University",
  "Covenant University",
  "Crawford University",
  "Crescent University",
  "Delta State University of Science and Technology",
  "Delta State University, Abraka",
  "Dennis Osadebay University",
  "Dominican University Ibadan",
  "Ebonyi State University",
  "Edo State University, Uzairue",
  "Edwin Clark University",
  "Ekiti State University",
  "Elizade University",
  "Emmanuel Ayande University of Education",
  "Enugu State University of Science and Technology",
  "Evangel University, Akaeze",
  "Federal University Birnin Kebbi",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University of Agriculture Abeokuta",
  "Federal University of Agriculture Mubi",
  "Federal University of Agriculture Zuru",
  "Federal University of Applied Sciences Kachia",
  "Federal University of Education Pankshi",
  "Federal University of Education Zaria",
  "Federal University of Health Sciences Azare",
  "Federal University of Petroleum Resources Effurun",
  "Federal University of Technology Akure",
  "Federal University of Technology Ikot Abasi",
  "Federal University of Technology Minna",
  "Federal University of Technology Owerri",
  "Federal University of Transportation Daura",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Fountain University",
  "Godfrey Okoye University",
  "Gombe State University",
  "Gombe State University of Science and Technology",
  "Greenfield University",
  "Gregory University",
  "Hallmark University",
  "Hezekiah University",
  "Ibrahim Badamasi Babangida University",
  "Igbinedion University",
  "Ignatius Ajuru University of Education",
  "Imo State University",
  "James Hope University, Lagos",
  "Joseph Ayo Babalola University",
  "Joseph Sarwuan Tarka University",
  "Kaduna State University",
  "Kebbi State University of Science and Technology",
  "Khadija University",
  "Kings University",
  "Kingsley Ozumba Mbadiwe University",
  "Koladaisi University",
  "Kwara State University",
  "Kwararafa University",
  "Ladoke Akintola University of Technology",
  "Lagos State University",
  "Lagos State University of Education",
  "Lagos State University of Science and Technology",
  "Landmark University",
  "Lead City University",
  "Legacy University Okija",
  "Madonna University",
  "McPherson University",
  "Mewar University",
  "Michael and Cecilia Ibru University",
  "Michael Okpara University of Agriculture Umudike",
  "Modibbo Adama University Yola",
  "Mountain Top University",
  "Mudiame University",
  "Nasarawa State University",
  "National Open University of Nigeria",
  "Niger Delta University",
  "Nigeria Police Academy Wudil",
  "Nigerian Army University Biu",
  "Nigerian Defence Academy",
  "Nigerian Maritime University",
  "Nigerian University of Technology and Management",
  "Nile University of Nigeria",
  "Nnamdi Azikiwe University",
  "Nok University Kachia",
  "Novena University",
  "Obafemi Awolowo University",
  "Obong University",
  "Oduduwa University",
  "Olabisi Onabanjo University",
  "Olusegun Agagu University of Science and Technology",
  "Osun State University",
  "PAMO University of Medical Sciences",
  "Pan-Atlantic University",
  "Paul University",
  "Peaceland University",
  "Plateau State University",
  "Precious Cornerstone University",
  "Prince Abubakar Audu University",
  "Redeemer's University Nigeria",
  "Renaissance University",
  "Rhema University",
  "Ritman University",
  "Rivers State University",
  "Salem University",
  "Sam Maris University",
  "Samuel Adegboyega University",
  "Skyline University",
  "Sokoto State University",
  "Sule Lamido University",
  "Summit University",
  "Tai Solarin Federal University of Education",
  "Taraba State University",
  "Umaru Musa Yar'adua University",
  "University of Abuja",
  "University of Benin",
  "University of Calabar",
  "University of Cross River State",
  "University of Delta",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Mkar",
  "University of Nigeria Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Usmanu Danfodiyo University",
  "Veritas University",
  "Wesley University",
  "Western Delta University",
  "Westland University",
  "Yobe State University",
  "Yusuf Maitama Sule Federal University of Education Kano",
  "Yusuf Maitama Sule University Kano",
  "Zamfara State University",
] as const;

export const registerSchema = z.object({
  body: z.object({
    email: z.string().email(),
    password: passwordSchema,
    firstName: z.string().min(1),
    lastName: z.string().min(1),
    // Optional at the API level (existing/other callers shouldn't break over a new
    // marketing-context field) -- the register form itself enforces a real choice via
    // required <select> elements, so every genuine signup still provides both.
    location: z.enum(LOCATIONS).default("Nigeria"),
    courseInterest: z.enum(COURSE_INTERESTS).optional(),
    university: z.enum(REGISTRATION_STATUSES).optional(),
    // Optional ambassador code from a ?ref= link or word of mouth. Lenient on purpose:
    // an unknown/blank code is silently ignored by referral.service, never a signup error.
    referralCode: z.string().trim().max(40).optional(),
  }),
});

export const loginSchema = z.object({
  body: z.object({
    email: z.string().email(),
    password: z.string().min(1),
  }),
});

export const passwordResetRequestSchema = z.object({
  body: z.object({
    email: z.string().email(),
  }),
});

export const passwordResetConfirmSchema = z.object({
  body: z.object({
    token: z.string().min(1),
    password: passwordSchema,
  }),
});

export const verifyEmailSchema = z.object({
  body: z.object({
    token: z.string().min(1),
  }),
});
