import { Button } from "./Button";
import { Modal } from "./Modal";

export const AI_DETECTED_TITLE = "AI-Generated Answer Detected — Submission Not Accepted";

interface AiDetectedDialogProps {
  message?: string | null;
  onClose: () => void;
}

// Shown when the server rejects a submission because the typed answer or attached file
// reads as AI-generated. The candidate must rewrite the answer in their own words.
export function AiDetectedDialog({ message, onClose }: AiDetectedDialogProps) {
  return (
    <Modal title={AI_DETECTED_TITLE} onClose={onClose}>
      <div role="alertdialog" aria-label={AI_DETECTED_TITLE} className="flex flex-col gap-4">
        <p className="text-gray-700">
          {message ??
            "Your answer appears to have been generated by an AI tool. Please rewrite it in your own words, based on what you learned in the lessons, and resubmit."}
        </p>
        <p className="text-sm text-gray-500">
          Your submission has not been saved. Write your answer yourself, in your own words, using
          your own examples, then submit it again.
        </p>
        <div className="flex justify-end">
          <Button type="button" onClick={onClose}>
            Rewrite my answer
          </Button>
        </div>
      </div>
    </Modal>
  );
}
